### ISSUE TITLE
Missing "=" in comment line

### ISSUE THREAD

**Issue by xrotwang** [UniversalDependencies/UD_Munduruku-TuDeT#1]
The comment line here: https://github.com/UniversalDependencies/UD_Munduruku-TuDeT/blob/6974481c55d5225872e18e0bf8a5990254e9957b/myu_tudet-ud-test.conllu#L586
is missing a `=` to separate key from value. Thus, the metadata isn't parsed correctly, e.g.by the `conllu` package.

**Comment by xrotwang** [comment]
@LanguageStructure could you fix this problem?

**Comment by xrotwang** [comment]
@LanguageStructure do we want to get this fix into the first release?

**Comment by LanguageStructure** [comment]
I am looking at it right now.
Didi you fork Makurap?
